# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tH4pPj0-6iwHsq5Ix21z7Dfa4vuJYYtA
"""

import streamlit as st
import tensorflow as tf
from tensorflow.keras.preprocessing import image
import numpy as np
from PIL import Image
import os

st.set_page_config(page_title="Alzheimer Detection", layout="wide")
st.title("🧠 Alzheimer’s Detection using MobileNetV2")

# Load model
MODEL_PATH = os.path.join("Models", "mobilenetv2_alzheimer_finetuned.h5")
@st.cache_resource
def load_model():
    model = tf.keras.models.load_model(MODEL_PATH)
    return model

model = load_model()
st.success("✅ Model loaded successfully!")

# File uploader
uploaded_file = st.file_uploader("Upload an MRI image", type=["jpg", "jpeg", "png"])
if uploaded_file is not None:
    img = Image.open(uploaded_file).convert("RGB")
    st.image(img, caption="Uploaded MRI", use_column_width=True)

    # Preprocess
    img = img.resize((224, 224))
    x = image.img_to_array(img)
    x = np.expand_dims(x, axis=0) / 255.0

    # Predict
    preds = model.predict(x)
    class_names = ["Mild Demented", "Moderate Demented", "Non Demented", "Very Mild Demented"]
    pred_class = class_names[np.argmax(preds)]

    st.subheader("🩺 Prediction Result")
    st.write(f"**{pred_class}**")